### ISSUE TITLE
Vagrant provision does not run rsync

### ISSUE THREAD

**Issue by derks** [jeefy/vagrant-packet#7]
Running `vagrant provision` after the initial `vagrant up` does not appear to do anything, though it should rerun rsync of any `vm.synced_folder` definitions.

- Vagrant: 2.1.5
- Packet Plugin: 0.1.6

**Comment by jeefy** [comment]
This is by design. The folder-sync step is part of the core of Vagrant. [Here](https://www.vagrantup.com/docs/synced-folders/rsync.html) is some specific info about the RSync workflow.

If you need to push changes up, you can either run `vagrant rsync` (one-time sync) or `vagrant rsync-auto` (see https://www.vagrantup.com/docs/cli/rsync-auto.html for more info)

If you think there's a good use-case to add the RSync action into the provisioning step let me know. :)

Thanks!

**Comment by derks** [comment]
Right on, wasn't aware of those sub-commands...  with VirtualBox I've just always run `vagrant provision` to resync... but this is obviously better.  Thanks.
